### ISSUE TITLE
Add dynamic property in send

### ISSUE THREAD

**Issue by thejoe8495** [dlid/Dlid.MiHome#8]
I don't find a way to give Json like object to the robot, i add dynamic object to send it. For example this is need for install sounds or firmware update. 

>        public MiHomeResponse Send(string methodName, dynamic parameters) {
>            var miRequest = new MiHomeRequest(_miToken, _deviceId, _serverTimestamp, >NetworkOptions, new {
>                method = methodName,
>                @params = parameters
>            }, _log);
>            return Send(miRequest);
>        }

Simple usage:
>             dynamic jsonObject = new JObject();
>             jsonObject.sid = 1;
>             jsonObject.url = (ws.baseurl + localfile.Replace("\\", "/"));
>             jsonObject.md5 = CalculateMD5(localfile);
> 
>             var device = new MiDevice(**IP**, **TOKEN**);
>             device.Send("dnld_install_sound", jsonObject);

when i use the params function i get an array and inside one object. Or is there a other object/way to create this JSON?

**Comment by dlid** [comment]
Hi!

The Send-method that accept the method name is meant for the average command - I believe most of them will take an array of parameters so that's why I created this overload to easily invoke most commands.

But is a version of Send -  `Send(object data)` - that will allow you to send any data, but then you must also specify the method name in your object.

```
dynamic jsonObject = new JObject();
jsonObject.method = "dnld_install_sound";
jsonObject.@params = new {
 sid = 1,
 url = (ws.baseurl + localfile.Replace("\\", "/")),
 md5 = CalculateMD5(localfile)
};

var device = new MiDevice(**IP**, **TOKEN**);
device.Send(jsonObject);
```

I hope that will make it possible for you to create your install_sound request properly.

Regards
David

**Comment by thejoe8495** [comment]
Hi i try it but i became a error:
System.ArgumentException: "Could not determine JSON object type for type <>f__AnonymousType1`3[System.Int32,System.String,System.String]."
![image](https://user-images.githubusercontent.com/15785677/71447605-b9f55d00-2730-11ea-8a8f-5265f7a06963.png)

But for the readme i can create the object with:
```
            dynamic jsonObject = new JObject();
            jsonObject.method = "dnld_install_sound";
            jsonObject.@params = new JObject();
            jsonObject.@params.sid = 1;
            jsonObject.@params.url = ws.baseurl + localfile.Replace("\\", "/");
            jsonObject.@params.md5 = CalculateMD5(localfile);
```
Thank you i use this lines.

**Comment by dlid** [comment]
Ah ok, I never tried it out with the JObject so I take it it's an issue with how that one is serializing anonymous objects .

I usually just use anonymous objects so I would choose to do it like this:

```
using(var device = new MiDevice("**IP**", "**TOKEN**")) {
 device.Send(new {
  method = "dnld_install_sound",
  @params = new {
   sid = 1,
   url = (ws.baseurl + localfile.Replace("\\", "/")),
   md5 = CalculateMD5(localfile)
   }
 });
}
```
Glad it worked out though!

**Comment by thejoe8495** [comment]
Ok yes this work too. But i love the dynamics a little more, when i want i can extend the dynamic at a later point ;)
```
            var test = new {
                method = "dnld_install_sound",
                @params = new {
                    sid = 1,
                    url = (ws.baseurl + localfile.Replace("\\", "/")),
                    md5 = CalculateMD5(localfile)
                }
            };
```
